# Configuration for support-requests - https://github.com/bahdcoder/nesabox-issues

# Label used to mark issues as support requests
supportLabel: support

# Comment to post on issues marked as support requests, `{issue-author}` is an
# optional placeholder. Set to `false` to disable
supportComment: >
  :wave: @{issue-author}, we use the issue tracker exclusively for bug reports
  and feature requests. However, this issue appears to be a support request.
  If you're Pro license holder, feel free to contact support at 
  admin@nesabox.com.
# Close issues marked as support requests
close: true

# Lock issues marked as support requests
lock: true

# Assign `off-topic` as the reason for locking. Set to `false` to disable
setLockReason: true
# Repository to extend settings from
# _extends: repo
